Repository jenkinsci/remoting, pull requests merged in 2019-06, with the labels that each got.

#318 [JENKINS-50095] Check for Remoting minimum version when connecting to master
  pom.xml
  src/findbugs/excludeFilter.xml
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: enhancement, ready-to-merge

#324 Fix typo in Selector wakeup thread messages
  src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
Labels: bugfix, ready-to-merge

#326 [JENKINS-57959] Remove final from args4j fields
  src/main/java/hudson/remoting/jnlp/Main.java
Labels: ready-to-merge
