Repository jenkinsci/remoting, pull requests merged in 2019-11, with the labels that each got.

#346 Fix missing `@since` annotations in Javadoc
  src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
  src/main/java/hudson/remoting/Channel.java
  src/main/java/hudson/remoting/NamingThreadFactory.java
  src/main/java/hudson/remoting/RemoteClassLoader.java
  src/main/java/hudson/remoting/RemoteInvocationHandler.java
  src/main/java/org/jenkinsci/remoting/protocol/ProtocolLayer.java
  src/main/java/org/jenkinsci/remoting/util/ByteBufferQueue.java
  src/main/java/org/jenkinsci/remoting/util/ByteBufferQueueInputStream.java
  src/main/java/org/jenkinsci/remoting/util/ByteBufferQueueOutputStream.java
  src/main/java/org/jenkinsci/remoting/util/ByteBufferUtils.java
  src/main/java/org/jenkinsci/remoting/util/FastByteBufferQueueInputStream.java
  src/main/java/org/jenkinsci/remoting/util/IOUtils.java
  src/main/java/org/jenkinsci/remoting/util/SettableFuture.java
  src/main/java/org/jenkinsci/remoting/util/ThrowableUtils.java
Labels: documentation, ready-to-merge

#347 Remove engineutil usage
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
Labels: chore, ready-to-merge

#348 Cleanup deprecated code
  src/test/java/hudson/remoting/ChannelFilterTest.java
  src/test/java/hudson/remoting/DiagnosedStreamCorruptionExceptionTest.java
  src/test/java/hudson/remoting/ForkRunner.java
  src/test/java/hudson/remoting/throughput/Receiver.java
  src/test/java/hudson/remoting/throughput/Sender.java
  src/test/java/org/jenkinsci/remoting/engine/ChannelCiphersTest.java
  src/test/java/org/jenkinsci/remoting/engine/EngineUtilTest.java
  src/test/java/org/jenkinsci/remoting/engine/HandshakeCiphersTest.java
  src/test/java/org/jenkinsci/remoting/engine/Jnlp3UtilTest.java
Labels: chore, ready-to-merge

#349 Add -version and -help
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/Util.java
  src/main/java/hudson/remoting/jnlp/Main.java
Labels: enhancement, ready-to-merge

#350 Use more common MIT license URL
  pom.xml
Labels: chore, ready-to-merge

#351 Clean up "slave" term from documentation.
  CHANGELOG-2.x.md
  CHANGELOG.md
  README.md
  docs/configuration.md
  docs/logging.md
  docs/protocols.md
  docs/remoting-3-compatibility.md
  docs/tcpAgent.md
  docs/workDir.md
  src/main/java/org/jenkinsci/remoting/engine/HandshakeCiphers.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol1Handler.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol2Handler.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol3Handler.java
  src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
  src/test/java/hudson/remoting/TrafficAnalyzer.java
  src/test/java/org/jenkinsci/remoting/engine/HandshakeCiphersTest.java
Labels: chore, ready-to-merge

#352 Remove internal usages of "slave" term.
  src/main/java/org/jenkinsci/remoting/engine/HandshakeCiphers.java
Labels: chore, ready-to-merge
