Repository jenkinsci/remoting, pull requests merged in 2019-08, with the labels that each got.

#334 Remove FindBugs filter for hudson.util.VersionNumber
  src/findbugs/excludeFilter.xml
Labels: ready-to-merge

#336 Replace tabs with spaces
  src/assembly/agent-load-test/agent-load-test
  src/main/java/hudson/remoting/ClassFilter.java
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/RemoteClassLoader.java
  src/main/java/hudson/remoting/UserRequest.java
  src/main/java/hudson/remoting/jnlp/Main.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: chore, ready-to-merge

#340 Enable Release Drafter.
  .github/release-drafter.yml
Labels: chore

#343 Update "@since TODO" tags.
  docs/tcpAgent.md
  src/main/java/hudson/remoting/Callable.java
  src/main/java/hudson/remoting/Channel.java
  src/main/java/hudson/remoting/ChannelClosedException.java
  src/main/java/hudson/remoting/Command.java
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/ExportTable.java
  src/main/java/hudson/remoting/ProxyWriter.java
  src/main/java/hudson/remoting/URLDeserializationHelper.java
  src/main/java/hudson/remoting/jnlp/Main.java
  src/main/java/org/jenkinsci/remoting/CallableDecorator.java
  src/main/java/org/jenkinsci/remoting/ChannelStateException.java
  src/main/java/org/jenkinsci/remoting/Role.java
  src/main/java/org/jenkinsci/remoting/engine/EngineUtil.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
  src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
  src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
  src/main/java/org/jenkinsci/remoting/util/PathUtils.java
  src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java
Labels: chore
