Repository jenkinsci/remoting, pull requests merged in 2019-12, with the labels that each got.

#358 Publish Incrementals
  Jenkinsfile
  pom.xml
  src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java
Labels: chore, ready-to-merge

#356 Complete the transition to spotbugs.
  pom.xml
  src/spotbugs/excludeFilter.xml
Labels: chore, ready-to-merge

#363 README: Update the changelog badge label to be more explicit
  README.md
Labels: documentation

#355 Upgrade the parent POM from 1.52 to 1.53
  pom.xml
Labels: chore

#360 Remove test protocol from production code.
  docs/protocols.md
  src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol4PlainHandler.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpProtocolHandlerFactory.java
  src/test/java/org/jenkinsci/remoting/engine/JnlpProtocolHandlerTest.java
Labels: chore, ready-to-merge

#361 Add findsecbugs plugin to spotbugs.
  pom.xml
  src/main/java/hudson/remoting/Capability.java
  src/main/java/hudson/remoting/Checksum.java
  src/main/java/hudson/remoting/ClassFilter.java
  src/main/java/hudson/remoting/Command.java
  src/main/java/hudson/remoting/DiagnosedStreamCorruptionException.java
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/FileSystemJarCache.java
  src/main/java/hudson/remoting/InitializeJarCacheMain.java
  src/main/java/hudson/remoting/JarLoaderImpl.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/Pipe.java
  src/main/java/hudson/remoting/RemoteClassLoader.java
  src/main/java/hudson/remoting/RemoteInputStream.java
  src/main/java/hudson/remoting/RemoteInvocationHandler.java
  src/main/java/hudson/remoting/ResourceImageDirect.java
  src/main/java/hudson/remoting/ResourceImageInJar.java
  src/main/java/hudson/remoting/URLDeserializationHelper.java
  src/main/java/hudson/remoting/UserRequest.java
  src/main/java/hudson/remoting/Util.java
  src/main/java/hudson/remoting/Which.java
  src/main/java/hudson/remoting/forward/ForwarderFactory.java
  src/main/java/hudson/remoting/forward/PortForwarder.java
  src/main/java/hudson/remoting/jnlp/GuiListener.java
  src/main/java/hudson/remoting/jnlp/Main.java
  src/main/java/org/jenkinsci/remoting/engine/ChannelCiphers.java
  src/main/java/org/jenkinsci/remoting/engine/HandshakeCiphers.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
  src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
  src/main/java/org/jenkinsci/remoting/protocol/cert/BlindTrustX509ExtendedTrustManager.java
  src/main/java/org/jenkinsci/remoting/protocol/cert/PublicKeyMatchingX509ExtendedTrustManager.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/AckFilterLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionRefusalException.java
  src/main/java/org/jenkinsci/remoting/util/KeyUtils.java
  src/main/java/org/jenkinsci/remoting/util/https/NoCheckHostnameVerifier.java
  src/main/java/org/jenkinsci/remoting/util/https/NoCheckTrustManager.java
  src/spotbugs/excludeFilter.xml
Labels: chore, ready-to-merge

#362 Modernize source code up to Java 8
  src/main/java/hudson/remoting/AbstractByteArrayCommandTransport.java
  src/main/java/hudson/remoting/BinarySafeStream.java
  src/main/java/hudson/remoting/Channel.java
  src/main/java/hudson/remoting/CommandTransport.java
  src/main/java/hudson/remoting/FastPipedOutputStream.java
  src/main/java/hudson/remoting/FileSystemJarCache.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/RemoteClassLoader.java
  src/main/java/hudson/remoting/RemoteInvocationHandler.java
  src/main/java/hudson/remoting/UserRequest.java
  src/main/java/hudson/remoting/Util.java
  src/main/java/hudson/remoting/VirtualChannel.java
  src/main/java/hudson/remoting/Which.java
  src/main/java/hudson/remoting/jnlp/Main.java
  src/main/java/org/jenkinsci/remoting/engine/EngineUtil.java
  src/main/java/org/jenkinsci/remoting/engine/HandshakeCiphers.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol2Handler.java
  src/main/java/org/jenkinsci/remoting/engine/LegacyJnlpConnectionState.java
  src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
  src/main/java/org/jenkinsci/remoting/util/AnonymousClassWarnings.java
  src/main/java/org/jenkinsci/remoting/util/VersionNumber.java
  src/test/java/hudson/remoting/BinarySafeStreamTest.java
  src/test/java/hudson/remoting/DeadRemoteOutputStreamTest.java
  src/test/java/hudson/remoting/DummyClassLoader.java
  src/test/java/hudson/remoting/RegExpBenchmark.java
  src/test/java/hudson/remoting/RemoteInputStreamTest.java
  src/test/java/hudson/remoting/SimpleTest.java
  src/test/java/org/jenkinsci/remoting/nio/FifoBufferTest.java
  src/test/java/org/jenkinsci/remoting/protocol/IOBufferMatcher.java
  src/test/java/org/jenkinsci/remoting/protocol/IOHubTest.java
  src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackImplTest.java
  src/test/java/org/jenkinsci/remoting/protocol/impl/AckFilterLayerTest.java
  src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayerTest.java
  src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersTest.java
  src/test/java/org/jenkinsci/remoting/protocol/impl/NetworkLayerTest.java
  src/test/java/org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayerTest.java
Labels: chore, ready-to-merge
