Repository jenkinsci/remoting, pull requests merged in 2020-04, with the labels that each got.

#374 Broaden the scope of Thread.name inclusion to whole Request.call body
  src/main/java/hudson/remoting/Request.java
Labels: enhancement, ready-to-merge

#375 Minor JNLP parsing improving, mostly in testing
  src/main/java/hudson/remoting/Launcher.java
  src/test/java/hudson/remoting/LauncherTest.java
  src/test/resources/hudson/remoting/embedded_doctype.jnlp
  src/test/resources/hudson/remoting/lol.jnlp
  src/test/resources/hudson/remoting/note.dtd
  src/test/resources/hudson/remoting/test.jnlp
  src/test/resources/hudson/remoting/xxe_file.jnlp
  src/test/resources/hudson/remoting/xxe_http.jnlp
Labels: chore, ready-to-merge

#376 Cleanup and modernization for RemoteClassLoader
  src/main/java/hudson/remoting/DumbClassLoaderBridge.java
  src/main/java/hudson/remoting/RemoteClassLoader.java
  src/test/java/hudson/remoting/ClassRemotingTest.java
Labels: chore, ready-to-merge

#377 Auto-format RemoteClassLoader.
  src/main/java/hudson/remoting/RemoteClassLoader.java
Labels: ready-to-merge
