Repository jenkinsci/remoting, pull requests merged in 2020-10, with the labels that each got.

#397 Use Warning-NG instead of findbugs.
  Jenkinsfile
Labels: chore

#391 Add protection against missing trailing slashes when using websocket.
  src/main/java/hudson/remoting/Engine.java
Labels: bug, ready-to-merge

#392 RemoteInvocationHandler.reportStats LogRecord’s could get mangled during serialization
  src/main/java/hudson/remoting/RemoteInvocationHandler.java
Labels: bug, ready-to-merge

#393 [JENKINS-63118] delete /tmp/resource-xxx on exit
  src/main/java/hudson/remoting/Util.java
Labels: bug, ready-to-merge

#407 Update to the latest parent pom.
  pom.xml
Labels: dependencies, ready-to-merge

#408 Upgrade asm
  pom.xml
  src/test/java/hudson/remoting/ClassRemotingTest.java
  src/test/java/hudson/remoting/PrefetchTest.java
Labels: dependencies, ready-to-merge

#412 Upgrade bouncy castle
  pom.xml
Labels: dependencies, ready-to-merge

#416 Remove obsolete log alias.
  src/main/java/hudson/remoting/Launcher.java
Labels: ready-to-merge, remove

#417 Improve documentation, removing more instances of 'slave' term.
  docs/inbound-agent.md
  src/main/java/hudson/remoting/jnlp/Main.java
  src/main/java/hudson/remoting/jnlp/package-info.java
Labels: documentation, ready-to-merge

#418 Update maven-assembly plugin.
  pom.xml
Labels: dependencies, ready-to-merge

#420 Upgrade parent pom, fixing issue with previous one.
  pom.xml
Labels: dependencies, ready-to-merge
