Repository jenkinsci/remoting, pull requests merged in 2021-04, with the labels that each got.

#444 Migrate from SettableFuture to CompletableFuture in tests
  src/test/java/org/jenkinsci/remoting/engine/HandlerLoopbackLoadStress.java
  src/test/java/org/jenkinsci/remoting/protocol/IOBufferMatcher.java
  src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackLoopbackLoadStress.java
  src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayerTest.java
Labels: chore, ready-to-merge

#441 Disable stacktraces from ExportTable entries by default
  src/main/java/hudson/remoting/ExportTable.java
  src/test/java/hudson/remoting/ExportTableTest.java
Labels: ready-to-merge, remove

#445 [JENKINS-63520] Sequence the startup and receiving to avoid a deadlock.
  src/main/java/org/jenkinsci/remoting/protocol/ProtocolStack.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/BIONetworkLayer.java
Labels: bug, ready-to-merge
