Repository jenkinsci/remoting, pull requests merged in 2021-02, with the labels that each got.

#437 Update to parent 1.63.
  pom.xml
  src/main/java/hudson/remoting/NoProxyEvaluator.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: dependencies, ready-to-merge

#422 Undeprecate KeyUtils.fingerprint
  src/main/java/org/jenkinsci/remoting/util/KeyUtils.java
Labels: documentation, ready-to-merge

#428 Collection of various minor cleanups.
  src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
  src/main/java/hudson/remoting/AtmostOneThreadExecutor.java
  src/main/java/hudson/remoting/Base64.java
  src/main/java/hudson/remoting/BinarySafeStream.java
  src/main/java/hudson/remoting/ChannelBuilder.java
  src/main/java/hudson/remoting/Checksum.java
  src/main/java/hudson/remoting/ClassFilter.java
  src/main/java/hudson/remoting/DelegatingCallable.java
  src/main/java/hudson/remoting/DelegatingExecutorService.java
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/ExportTable.java
  src/main/java/hudson/remoting/ExportedClassLoaderTable.java
  src/main/java/hudson/remoting/FastPipedInputStream.java
  src/main/java/hudson/remoting/InitializeJarCacheMain.java
  src/main/java/hudson/remoting/InterceptingExecutorService.java
  src/main/java/hudson/remoting/LocalChannel.java
  src/main/java/hudson/remoting/Pipe.java
  src/main/java/hudson/remoting/ProxyInputStream.java
  src/main/java/hudson/remoting/ProxyWriter.java
  src/main/java/hudson/remoting/ReferenceCountRecorder.java
  src/main/java/hudson/remoting/RemoteInputStream.java
  src/main/java/hudson/remoting/RemoteInvocationHandler.java
  src/main/java/hudson/remoting/Response.java
  src/main/java/hudson/remoting/VirtualChannel.java
  src/main/java/hudson/remoting/jnlp/GUI.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointConfigurator.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpConnectionState.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol4Handler.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpProtocolHandlerFactory.java
  src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java
  src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
  src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
  src/main/java/org/jenkinsci/remoting/protocol/IOHubReadyListener.java
  src/main/java/org/jenkinsci/remoting/protocol/NetworkLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/AckFilterLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/AgentProtocolClientFilterLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.java
  src/main/java/org/jenkinsci/remoting/util/ByteBufferQueue.java
  src/main/java/org/jenkinsci/remoting/util/ByteBufferQueueInputStream.java
  src/main/java/org/jenkinsci/remoting/util/Charsets.java
  src/main/java/org/jenkinsci/remoting/util/DirectByteBufferPool.java
  src/main/java/org/jenkinsci/remoting/util/ExecutorServiceUtils.java
  src/main/java/org/jenkinsci/remoting/util/https/NoCheckTrustManager.java
  src/test/java/hudson/remoting/ClassFilterTest.java
  src/test/java/hudson/remoting/ExportTableTest.java
Labels: chore, ready-to-merge

#429 [JENKINS-64510] Issues with TCP agent reconnects
  src/main/java/org/jenkinsci/remoting/engine/JnlpConnectionState.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpProtocol4Handler.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
Labels: bug, ready-to-merge

#435 Remove hardcode of JKS for use other key stores
  src/main/java/hudson/remoting/Engine.java
  src/test/java/org/jenkinsci/remoting/engine/HandlerLoopbackLoadStress.java
  src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackLoopbackLoadStress.java
  src/test/java/org/jenkinsci/remoting/protocol/cert/SSLContextRule.java
Labels: enhancement, ready-to-merge

#379 [JENKINS-61103] Retry on class resource load failures and introduce timeouts
  src/main/java/hudson/remoting/RemoteClassLoader.java
  src/test/java/hudson/remoting/ClassRemoting2Test.java
  src/test/java/hudson/remoting/ClassRemotingTest.java
  src/test/java/hudson/remoting/ForkRunner.java
  src/test/java/hudson/remoting/TestStaticGetResources.java
  src/test/java/hudson/remoting/TestStaticResourceReference.java
Labels: bug, ready-to-merge

#440 Add url to fix dependabot release notes
  pom.xml
Labels: chore
