Repository jenkinsci/remoting, pull requests merged in 2021-09, with the labels that each got.

#481 Remove setting of null security manager
  src/main/java/hudson/remoting/jnlp/Main.java
Labels: ready-to-merge, chore

#479 No more `@IgnoreJRERequirement`s
  src/main/java/org/jenkinsci/remoting/protocol/cert/BlindTrustX509ExtendedTrustManager.java
  src/main/java/org/jenkinsci/remoting/protocol/cert/PublicKeyMatchingX509ExtendedTrustManager.java
  src/main/java/org/jenkinsci/remoting/protocol/cert/ValidityCheckingX509ExtendedTrustManager.java
Labels: chore

#480 Remove unused `ProtocolLayer#UTF_8` field
  src/main/java/org/jenkinsci/remoting/protocol/ProtocolLayer.java
Labels: chore

#478 [JENKINS-61212] Update Tyrus (WebSocket client) to 1.18
  pom.xml
Labels: dependencies
