Repository jenkinsci/remoting, pull requests merged in 2021-05, with the labels that each got.

#447 Update the url of HudsonArch-Remoting.pdf
  README.md
Labels: documentation

#450 [JENKINS-40700] Enable current engine to hold the communication protocol
  src/main/java/hudson/remoting/Engine.java
Labels: enhancement, ready-to-merge

#449 Allow JNLP agent endpoint resolution exceptions to be non-fatal for Swarm
  src/main/java/hudson/remoting/Engine.java
Labels: bug, ready-to-merge

#442 Various cleanups
  src/main/java/hudson/remoting/Channel.java
  src/main/java/hudson/remoting/ChannelBuilder.java
  src/main/java/hudson/remoting/ChunkedOutputStream.java
  src/main/java/hudson/remoting/DaemonThreadFactory.java
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/FastPipedInputStream.java
  src/main/java/hudson/remoting/FileSystemJarCache.java
  src/main/java/hudson/remoting/FlightRecorderInputStream.java
  src/main/java/hudson/remoting/ImportedClassLoaderTable.java
  src/main/java/hudson/remoting/JarCacheSupport.java
  src/main/java/hudson/remoting/JarLoaderImpl.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/PingThread.java
  src/main/java/hudson/remoting/RemoteClassLoader.java
  src/main/java/hudson/remoting/Request.java
  src/main/java/hudson/remoting/SynchronousCommandTransport.java
  src/main/java/hudson/remoting/forward/CopyThread.java
  src/main/java/hudson/remoting/forward/PortForwarder.java
  src/main/java/hudson/remoting/jnlp/Main.java
  src/main/java/org/jenkinsci/remoting/nio/FifoBuffer.java
  src/main/java/org/jenkinsci/remoting/nio/NioChannelHub.java
  src/main/java/org/jenkinsci/remoting/protocol/IOHub.java
  src/main/java/org/jenkinsci/remoting/protocol/cert/DelegatingX509ExtendedTrustManager.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/AgentProtocolClientFilterLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayer.java
  src/main/java/org/jenkinsci/remoting/util/SettableFuture.java
  src/test/java/org/jenkinsci/remoting/engine/HandlerLoopbackLoadStress.java
Labels: chore, ready-to-merge

#452 [JENKINS-40700] Enable Launcher to hold the communication protocol.
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Launcher.java
Labels: enhancement, ready-to-merge

#456 Update Guava
  pom.xml
Labels: dependencies

#458 Allow setting of custom websocket headers
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/jnlp/Main.java
Labels: enhancement, ready-to-merge

#454 Define `hudsonUrl` in WebSocket mode to fix agent installers
  src/main/java/hudson/remoting/Engine.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: bug, ready-to-merge
