Repository jenkinsci/remoting, pull requests merged in 2022-03, with the labels that each got.

#511 Clean up SpotBugs exclusions
  src/main/java/hudson/remoting/Capability.java
  src/main/java/hudson/remoting/Channel.java
  src/main/java/hudson/remoting/ClassFilter.java
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/GCCommand.java
  src/main/java/hudson/remoting/JarLoaderImpl.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/RemoteClassLoader.java
  src/main/java/hudson/remoting/jnlp/MainDialog.java
  src/main/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/RegexValidator.java
  src/main/java/org/jenkinsci/remoting/util/LoggingChannelListener.java
  src/main/java/org/jenkinsci/remoting/util/SettableFuture.java
  src/spotbugs/excludeFilter.xml
Labels: ready-to-merge, internal, squash-merge-me

#513 JENKINS-67928 Prevent infinite loop in case of closed SSL connection
  src/main/java/org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.java
Labels: ready-to-merge, bug

#514 JENKINS-66446 Agent reconnects on Java 11 and websocket
  src/main/java/hudson/remoting/Engine.java
Labels: ready-to-merge, bug, squash-merge-me

#517 Add Java 11 and 17 to build/test matrix
  Jenkinsfile
  pom.xml
  src/main/java/hudson/remoting/CommandTransport.java
Labels: test
