Repository jenkinsci/remoting, pull requests merged in 2022-05, with the labels that each got.

#530 Set tarLongFileMode to enable building on systems with large UID / GID
  pom.xml
Labels: chore

#534 Remove unneeded SUREFIRE-1226 workaround
  pom.xml
Labels: test

#523 [JENKINS-65873] Throttle anonymous class warnings to a single thread
  src/main/java/org/jenkinsci/remoting/util/AnonymousClassWarnings.java
Labels: bug, enhancement

#535 Suppress some uninteresting stack traces when channel is closed
  src/main/java/hudson/remoting/JarCacheSupport.java
  src/main/java/hudson/remoting/UserRequest.java
Labels: chore

#536 Push changes as part of release
  pom.xml
Labels: chore

#538 Enable CD (JEP-229)
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: chore

#537 [JENKINS-68542] [WebSocket] Capture cookie returned by server and reuse for reconnection attempts
  src/main/java/hudson/remoting/Engine.java
Labels: bug

#539 [JENKINS-68542] [WebSocket] Capture cookie returned by server and reuse for reconnection attempts
  src/main/java/hudson/remoting/Engine.java
Labels: bug

#542 [JENKINS-68542] Rename the header used for connection cookie
  src/main/java/hudson/remoting/Engine.java
Labels: bug
