Repository jenkinsci/remoting, pull requests merged in 2022-02, with the labels that each got.

#502 Replace deprecated APIs
  src/main/java/hudson/remoting/Channel.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/PingThread.java
  src/main/java/hudson/remoting/RemoteInvocationHandler.java
  src/test/java/JarCertDump.java
  src/test/java/hudson/remoting/ChecksumTest.java
  src/test/java/hudson/remoting/DefaultClassFilterTest.java
  src/test/java/hudson/remoting/DiagnosedStreamCorruptionExceptionTest.java
  src/test/java/hudson/remoting/DummyClassLoader.java
  src/test/java/hudson/remoting/FileSystemJarCacheTest.java
  src/test/java/hudson/remoting/PipeTest.java
  src/test/java/hudson/remoting/RmiTestBase.java
  src/test/java/hudson/remoting/throughput/DumbReceiver.java
  src/test/java/hudson/remoting/throughput/Sender.java
  src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java
  src/test/java/org/jenkinsci/remoting/protocol/IOHubTest.java
  src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersTest.java
Labels: chore

#507 [JENKINS-67000] Restore setting of null security manager
  src/main/java/hudson/remoting/jnlp/Main.java
Labels: bug

#510 Fix `ByteBuffer`-related Animal Sniffer errors
  src/main/java/hudson/remoting/AbstractByteBufferCommandTransport.java
  src/main/java/org/jenkinsci/remoting/protocol/FilterLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/NetworkLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/AckFilterLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/BIONetworkLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/NIONetworkLayer.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.java
  src/main/java/org/jenkinsci/remoting/util/ByteBufferQueue.java
  src/main/java/org/jenkinsci/remoting/util/ByteBufferQueueInputStream.java
  src/main/java/org/jenkinsci/remoting/util/ByteBufferUtils.java
  src/main/java/org/jenkinsci/remoting/util/DirectByteBufferPool.java
Labels: skip-changelog

#512 Minor internal improvements
  src/main/java/hudson/remoting/Channel.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.java
  src/main/java/org/jenkinsci/remoting/util/VersionNumber.java
  src/test/java/hudson/remoting/RegExpBenchmark.java
  src/test/java/org/jenkinsci/remoting/engine/HandlerLoopbackLoadStress.java
  src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackLoopbackLoadStress.java
Labels: ready-to-merge, skip-changelog, squash-merge-me
