Repository jenkinsci/remoting, pull requests merged in 2022-12, with the labels that each got.

#610 Better robustness for `RemoteIClassLoader.readResolve`
  src/main/java/hudson/remoting/RemoteClassLoader.java
Labels: bug

#611 Refresh documentation (particularly, screenshot) with the removed Launch button
  docs/inbound-agent.md
  docs/tcpAgentStatus.jpg
  docs/tcpAgentStatus.png
Labels: documentation

#612 Remove 2s timeout in `PipeTest.testReaderCloseWhileWriterIsStillWriting`
  src/test/java/hudson/remoting/PipeTest.java
Labels: test
