Repository jenkinsci/remoting, pull requests merged in 2022-07, with the labels that each got.

#551 Use Java 11 language features where possible
  src/main/java/hudson/remoting/Capability.java
  src/main/java/hudson/remoting/DumbClassLoaderBridge.java
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Which.java
  src/main/java/org/jenkinsci/remoting/Role.java
  src/main/java/org/jenkinsci/remoting/RoleChecker.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpConnectionState.java
  src/main/java/org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer.java
  src/test/java/OISInterception.java
  src/test/java/hudson/remoting/DefaultClassFilterTest.java
  src/test/java/hudson/remoting/DummyClassLoader.java
  src/test/java/hudson/remoting/EngineTest.java
  src/test/java/hudson/remoting/PrefetchingTest.java
  src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackImplTest.java
  src/test/java/org/jenkinsci/remoting/protocol/ProtocolStackLoopbackLoadStress.java
  src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersFilterLayerTest.java
  src/test/java/org/jenkinsci/remoting/protocol/impl/ConnectionHeadersTest.java
  src/test/java/org/jenkinsci/remoting/util/ByteBufferQueueInputStreamTest.java
  src/test/java/org/jenkinsci/remoting/util/FastByteBufferQueueInputStreamTest.java
Labels: ready-to-merge, chore

#567 [SECURITY] Fix Temporary Directory Information Disclosure Vulnerability in test
  src/test/java/hudson/remoting/PrefetchingTest.java
Labels: test

#559 [JENKINS-65873] [JENKINS-68954] Optimize `AnonymousClassWarnings`
  src/main/java/org/jenkinsci/remoting/util/AnonymousClassWarnings.java
Labels: bug

#569 Decrease timeout
  Jenkinsfile
Labels: skip-changelog
