Repository jenkinsci/remoting, pull requests merged in 2022-11, with the labels that each got.

#601 Simplify header parsing logic
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: internal

#602 Remove unused logo
  logo.xcf
Labels: chore

#603 [JENKINS-70105] Slow down websocket re-connect
  src/main/java/hudson/remoting/Engine.java
Labels: bug

#606 Remove unnecessary SpotBugs exclusions
  src/spotbugs/excludesFilter.xml
Labels: skip-changelog

#593 Support junit 5; Migrate non-forked junit 3 test cases
  pom.xml
  src/test/java/Driver8703.java
  src/test/java/hudson/remoting/AbstractNioChannelRunner.java
  src/test/java/hudson/remoting/BinarySafeStreamTest.java
  src/test/java/hudson/remoting/ChannelFilterTest.java
  src/test/java/hudson/remoting/ChannelRunner.java
  src/test/java/hudson/remoting/ChannelRunners.java
  src/test/java/hudson/remoting/ChannelTest.java
  src/test/java/hudson/remoting/ChannelTestSuite.java
  src/test/java/hudson/remoting/ClassRemoting2Test.java
  src/test/java/hudson/remoting/ClassRemotingTest.java
  src/test/java/hudson/remoting/DeadRemoteOutputStreamTest.java
  src/test/java/hudson/remoting/DummyClassLoaderTest.java
  src/test/java/hudson/remoting/ExportTableTest.java
  src/test/java/hudson/remoting/ForkRunner.java
  src/test/java/hudson/remoting/HexDumpTest.java
  src/test/java/hudson/remoting/InProcessRunner.java
  src/test/java/hudson/remoting/NonSerializableExceptionTest.java
  src/test/java/hudson/remoting/PipeTest.java
  src/test/java/hudson/remoting/PipeWriterTest.java
  src/test/java/hudson/remoting/PrefetchTest.java
  src/test/java/hudson/remoting/PrefetchingTest.java
  src/test/java/hudson/remoting/ProxyWriterTest.java
  src/test/java/hudson/remoting/RemoteInputStreamTest.java
  src/test/java/hudson/remoting/RemoteInvocationHandlerTest.java
  src/test/java/hudson/remoting/RmiTestBase.java
  src/test/java/hudson/remoting/SimpleTest.java
Labels: test
