Repository jenkinsci/remoting, pull requests merged in 2023-01, with the labels that each got.

#616 Document protocol stack
  docs/protocol-stack.dot
  docs/protocol-stack.png
  docs/protocols.md
Labels: documentation

#617 Generate SVG for protocol-stack
  docs/protocol-stack.png
  docs/protocol-stack.svg
  docs/protocols.md
Labels: chore

#620 Fix Maven Shade Plugin warnings
  pom.xml
Labels: internal

#619 `PipeTest.testReaderCloseWhileWriterIsStillWriting` is flaky; disabling
  src/test/java/hudson/remoting/PipeTest.java
Labels: test
