Repository jenkinsci/remoting, pull requests merged in 2023-08, with the labels that each got.

#660 Test on Java 21
  Jenkinsfile
Labels: chore

#661 Simplify test matrix
  Jenkinsfile
Labels: skip-changelog

#664 [JENKINS-38520] Every message in agent log appears twice with the `-agentLog` option
  src/main/java/hudson/remoting/TeeOutputStream.java
  src/test/java/hudson/remoting/TeeOutputStreamTest.java
Labels: bug

#665 Upgrade Apache Commons Validator from 1.6 to 1.7
  src/main/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/InetAddressValidator.java
  src/main/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/RegexValidator.java
  src/test/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/InetAddressValidatorTest.java
  src/test/java/org/jenkinsci/remoting/org/apache/commons/validator/routines/RegexValidatorTest.java
Labels: internal

#666 Upgrade Commons Net from 3.6 to 3.9.0
  src/main/java/org/jenkinsci/remoting/org/apache/commons/net/util/SubnetUtils.java
  src/test/java/org/jenkinsci/remoting/org/apache/commons/net/util/SubnetUtilsTest.java
Labels: dependencies, java
