Repository jenkinsci/remoting, pull requests merged in 2023-10, with the labels that each got.

#670 Test with `NullOutputStream.INSTANCE` instead of deprecated `NULL_OUTPUT_STREAM`
  src/test/java/hudson/remoting/ChannelRunner.java
  src/test/java/hudson/remoting/DiagnosedStreamCorruptionExceptionTest.java
  src/test/java/hudson/remoting/PipeTest.java
  src/test/java/hudson/remoting/PrefetchingTest.java
  src/test/java/hudson/remoting/throughput/DumbReceiver.java
  src/test/java/hudson/remoting/throughput/Sender.java
Labels: chore

#623 JENKINS-65368: isPortVisible did not take into account any proxy
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: bug

#675 [JENKINS-72163] Retry on initial connection failure occurs in one entrypoint but not the other
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: backporting-candidate, bug

#608 [JENKINS-72163] Add tests for agent endpoint resolution retries
  src/test/java/hudson/remoting/EngineTest.java
Labels: test

#678 Use Java 11 method where possible
  src/main/java/hudson/remoting/Launcher.java
Labels: internal

#680 Deprecating `PermanentConnectionRefusalException`
  src/main/java/org/jenkinsci/remoting/protocol/impl/PermanentConnectionRefusalException.java
Labels: documentation

#683 Better logging of controller URL from `JnlpAgentEndpointResolver`
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: enhancement

#681 Updating comment in `SocketChannelStream` about JDK-8222774
  src/main/java/hudson/remoting/SocketChannelStream.java
Labels: chore

#677 Unify two entrypoints
  docs/inbound-agent.md
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/Util.java
  src/main/java/hudson/remoting/jnlp/Main.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: internal

#685 Send `Node-Name` HTTP header in `JnlpAgentEndpointResolver`
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: enhancement

#687 Delete dead `Util.mkdirs`; inline use of `NoProxyEvaluator.shouldProxy`
  src/main/java/hudson/remoting/Util.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
  src/test/java/hudson/remoting/UtilTest.java
Labels: chore

#688 Fix proxy authentication
  src/main/java/hudson/remoting/Engine.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpoint.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointConfigurator.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: bug

#689 Fixing `-direct`
  src/main/java/hudson/remoting/Launcher.java
Labels: bug

#692 Increase visibility of field
  src/main/java/hudson/remoting/Launcher.java
Labels: skip-changelog

#690 Support `-cert` and `-noCertificateCheck` in WebSocket mode
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: enhancement

#691 Proxy support for WebSocket
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Launcher.java
Labels: enhancement

#693 Move initialization to common method for Swarm
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
Labels: bug

#694 Avoid capturing `Request` in `LogRecord` parameters
  src/main/java/hudson/remoting/Request.java
Labels: bug

#697 Remove deprecated `-cp` argument
  src/main/java/hudson/remoting/Launcher.java
Labels: removed

#696 Remove deprecated `Launcher#setNoCertificateCheck`
  src/main/java/hudson/remoting/Launcher.java
Labels: removed

#695 Log deprecation warning when using deprecated `hudson.remoting.jnlp.Main` entrypoint
  src/main/java/hudson/remoting/jnlp/Main.java
Labels: enhancement

#699 Print deprecation warning when deprecated arguments are used
  src/main/java/hudson/remoting/Launcher.java
Labels: enhancement

#700 Directly throw `IOException`
  src/main/java/hudson/remoting/Launcher.java
Labels: internal
