Repository jenkinsci/remoting, pull requests merged in 2024-01, with the labels that each got.

#708 Use spotbugs 4.8.2 with more exclusions
  pom.xml
  src/spotbugs/excludesFilter.xml
Labels: chore

#712 Update inbound agent documentation
  docs/inbound-agent.md
  docs/tcpAgentStatus.png
Labels: documentation

#711 Reduce visibility of `parseJnlpArguments`
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/jnlp/Main.java
Labels: internal

#713 Use `ConcurrentHashMap#computeIfAbsent` in `JarCacheSupport`
  src/main/java/hudson/remoting/JarCacheSupport.java
Labels: bug

#715 Use `CompletableFuture` in `JarCache`
  src/main/java/hudson/remoting/JarCache.java
  src/main/java/hudson/remoting/JarCacheSupport.java
  src/main/java/hudson/remoting/RemoteClassLoader.java
  src/main/java/hudson/remoting/ResourceImageBoth.java
  src/main/java/hudson/remoting/ResourceImageDirect.java
  src/main/java/hudson/remoting/ResourceImageInJar.java
  src/main/java/hudson/remoting/ResourceImageRef.java
Labels: internal

#716 Harden `JarCacheSupport`
  src/main/java/hudson/remoting/JarCacheSupport.java
Labels: internal

#717 Avoid continual thread replacement in `JarCacheSupport`
  src/main/java/hudson/remoting/JarCacheSupport.java
Labels: bug

#718 Rely on parent pom spotbugs configuration
  pom.xml
Labels: chore

#719 Use Java 11 methods where possible
  src/main/java/hudson/remoting/Checksum.java
  src/test/java/hudson/remoting/DiagnosedStreamCorruptionExceptionTest.java
  src/test/java/hudson/remoting/PipeTest.java
  src/test/java/hudson/remoting/throughput/DumbReceiver.java
  src/test/java/hudson/remoting/throughput/Sender.java
  src/test/java/org/jenkinsci/remoting/engine/WorkDirManagerTest.java
Labels: internal

#720 Add documentation about remote class loading subsystem
  docs/class-loading.md
Labels: documentation
