Repository jenkinsci/remoting, pull requests merged in 2024-10, with the labels that each got.

#765 Test with guava 33.3.1-jre, same as Jenkins core
  pom.xml
Labels: test

#767 Log the fact that a jar is being sent over channel
  src/main/java/hudson/remoting/JarLoaderImpl.java
Labels: developer

#769 Tolerate IPv6 scoped IPs from `JnlpAgentEndpointResolver.getResolvedHttpProxyAddress`
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
  src/test/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolverTest.java
Labels: bug

#706 Address `java.lang.NoClassDefFoundError` in `DefaultClassFilterTest` Through Fixed Order-Dependent Test Execution
  src/test/java/hudson/remoting/DefaultClassFilterTest.java
Labels: test
