Repository jenkinsci/remoting, pull requests merged in 2024-05, with the labels that each got.

#739 Fix incorrect classpath leading to broken tests
  src/test/java/hudson/remoting/ForkRunner.java
Labels: test

#738 Add `-noReconnectAfter` option
  src/main/java/hudson/remoting/Engine.java
  src/main/java/hudson/remoting/Launcher.java
  src/main/java/hudson/remoting/Util.java
  src/main/java/org/jenkinsci/remoting/DurationOptionHandler.java
  src/main/java/org/jenkinsci/remoting/engine/JnlpAgentEndpointResolver.java
  src/main/java/org/jenkinsci/remoting/util/DurationFormatter.java
  src/main/java/org/jenkinsci/remoting/util/DurationStyle.java
  src/test/java/org/jenkinsci/remoting/util/DurationFormatterTest.java
  src/test/java/org/jenkinsci/remoting/util/DurationStyleTest.java
Labels: enhancement

#741 Pass through the remote `ClassLoader`’s name
  src/main/java/hudson/remoting/DumbClassLoaderBridge.java
  src/main/java/hudson/remoting/RemoteClassLoader.java
Labels: enhancement

#743 Restore compatibility for older versions
  src/main/java/hudson/remoting/RemoteClassLoader.java
Labels: bug
